version: '3.4'

services:
  eshop:
    image: ${DOCKER_REGISTRY-}eshop
    build:
      context: .
      dockerfile: Eshop/Dockerfile
    depends_on:
      - db_postgres
  db_postgres:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: P@a55word
volumes:
  postgres_data: