version: '3.4'

services:
  eshop:
    image: ${DOCKER_REGISTRY-}eshop
    build:
      context: .
      dockerfile: Eshop/Dockerfile
    ports:
      - "22100:80"
      - "22101:443"
    depends_on:
      - db_postgres
  db_postgres:
    image: postgres:9.6.15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: P@a55word
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: